TEST_CASE_CATALOG = [
    {
        "id": "seed-bootstrap-helpers",
        "title": "Seed helpers and admin bootstrap",
        "area": "Platform",
        "health": "working",
        "status": "Automated",
        "summary": "Confirms admin seeding works and default room seeds stay disabled unless rooms are explicitly provided.",
        "source_file": "backend/tests/test_week1_smoke.py",
        "source_test": "test_00_seed_helpers",
        "commands": [
            "venv/bin/python -m unittest tests.test_week1_smoke.AppSmokeTest.test_00_seed_helpers",
        ],
        "covered_paths": [
            "seed helpers",
            "admin bootstrap",
            "room seed defaults",
        ],
    },
    {
        "id": "public-admin-shell-smoke",
        "title": "Public pages and admin shell smoke",
        "area": "Frontend",
        "health": "working",
        "status": "Automated",
        "summary": "Checks core pages, asset wiring, admin workspace markup, and bookings page shell content served by the backend.",
        "source_file": "backend/tests/test_week1_smoke.py",
        "source_test": "test_10_week_two_smoke_flow",
        "commands": [
            "venv/bin/python -m unittest tests.test_week1_smoke.AppSmokeTest.test_10_week_two_smoke_flow",
        ],
        "covered_paths": [
            "/",
            "/account",
            "/pricing",
            "/rooms",
            "/bookings",
            "/booking",
            "/admin",
            "/assets/js/main.js",
        ],
    },
    {
        "id": "customer-booking-flow-rules",
        "title": "Customer booking flow and business-hour rules",
        "area": "Bookings",
        "health": "working",
        "status": "Automated",
        "summary": "Verifies room availability, booking creation, one-per-day limits, duration constraints, and business-hour validation.",
        "source_file": "backend/tests/test_week1_smoke.py",
        "source_test": "test_20_week_three_booking_flow",
        "commands": [
            "venv/bin/python -m unittest tests.test_week1_smoke.AppSmokeTest.test_20_week_three_booking_flow",
        ],
        "covered_paths": [
            "/api/rooms/{room_id}/availability",
            "/api/bookings",
            "/bookings",
        ],
    },
    {
        "id": "pending-payment-expiry-window",
        "title": "Pending payment expiry and slot reopening",
        "area": "Bookings",
        "health": "working",
        "status": "Automated",
        "summary": "Confirms a saved booking expires after the payment window, switches to cancelled, and reopens the room slot.",
        "source_file": "backend/tests/test_week1_smoke.py",
        "source_test": "test_25_pending_payment_window_expires_and_reopens_slot",
        "commands": [
            "venv/bin/python -m unittest tests.test_week1_smoke.AppSmokeTest.test_25_pending_payment_window_expires_and_reopens_slot",
        ],
        "covered_paths": [
            "/api/bookings",
            "/api/bookings/{booking_id}",
            "/api/bookings/{booking_id}/payment-session",
            "/api/rooms/{room_id}/availability",
        ],
    },
    {
        "id": "admin-bookings-refunds-and-staff-conflicts",
        "title": "Admin bookings, refunds, and staff conflict handling",
        "area": "AdminOps",
        "health": "working",
        "status": "Automated",
        "summary": "Covers admin lookup, manual bookings, refund processing, schedule handling, and staff availability conflict checks.",
        "source_file": "backend/tests/test_week1_smoke.py",
        "source_test": "test_30_week_five_six_flow",
        "commands": [
            "venv/bin/python -m unittest tests.test_week1_smoke.AppSmokeTest.test_30_week_five_six_flow",
        ],
        "covered_paths": [
            "/api/admin/bookings",
            "/api/admin/bookings/manual",
            "/api/admin/bookings/{booking_id}/refund",
            "/api/admin/bookings/{booking_id}/check-in",
        ],
    },
    {
        "id": "account-delete-and-admin-visibility",
        "title": "Account deletion and admin account visibility",
        "area": "Accounts",
        "health": "working",
        "status": "Automated",
        "summary": "Checks masked saved-card details, self-delete, admin delete, and deleted-user booking identity retention.",
        "source_file": "backend/tests/test_week1_smoke.py",
        "source_test": "test_35_account_management_and_deleted_user_history",
        "commands": [
            "venv/bin/python -m unittest tests.test_week1_smoke.AppSmokeTest.test_35_account_management_and_deleted_user_history",
        ],
        "covered_paths": [
            "/api/users/me",
            "/api/admin/users",
            "/api/admin/bookings",
            "/account",
            "/admin",
        ],
    },
    {
        "id": "ops-notifications-and-background-jobs",
        "title": "Ops notifications and background-job coverage",
        "area": "Operations",
        "health": "working",
        "status": "Automated",
        "summary": "Covers account notifications, booking notifications, cleanup tasks, and administrative operational flows.",
        "source_file": "backend/tests/test_week1_smoke.py",
        "source_test": "test_40_week_seven_eight_ops",
        "commands": [
            "venv/bin/python -m unittest tests.test_week1_smoke.AppSmokeTest.test_40_week_seven_eight_ops",
        ],
        "covered_paths": [
            "/api/auth/signup",
            "/api/bookings",
            "celery cleanup tasks",
            "notification logs",
        ],
    },
    {
        "id": "five-hour-reminder-dispatch",
        "title": "Five-hour reminder dispatch schedule",
        "area": "Operations",
        "health": "working",
        "status": "Automated",
        "summary": "Checks the scheduled 5-hour reminder window and verifies both email and SMS reminders are dispatched once.",
        "source_file": "backend/tests/test_week1_smoke.py",
        "source_test": "test_40_week_seven_eight_ops",
        "commands": [
            "venv/bin/python -m unittest tests.test_week1_smoke.AppSmokeTest.test_40_week_seven_eight_ops",
        ],
        "covered_paths": [
            "dispatch-reminders-5h",
            "notification logs",
            "celery beat schedule",
        ],
    },
    {
        "id": "payment-confirmation-e2e",
        "title": "Payment confirmation end-to-end",
        "area": "Payments",
        "health": "working",
        "status": "Automated",
        "summary": "Exercises booking creation, payment session creation, Stripe webhook success, and notification persistence.",
        "source_file": "backend/tests/test_e2e_booking_payment.py",
        "source_test": "test_10_booking_payment_confirmation_e2e",
        "commands": [
            "venv/bin/python -m unittest tests.test_e2e_booking_payment.BookingPaymentE2ETest.test_10_booking_payment_confirmation_e2e",
        ],
        "covered_paths": [
            "/api/bookings",
            "/api/bookings/{booking_id}/payment-session",
            "/api/webhooks/stripe",
            "/booking",
        ],
    },
    {
        "id": "payment-failure-cancel-e2e",
        "title": "Payment failure cancellation fallback",
        "area": "Payments",
        "health": "working",
        "status": "Automated",
        "summary": "Verifies a failed Stripe webhook cancels the booking with the expected fallback reason.",
        "source_file": "backend/tests/test_e2e_booking_payment.py",
        "source_test": "test_20_booking_payment_failure_e2e",
        "commands": [
            "venv/bin/python -m unittest tests.test_e2e_booking_payment.BookingPaymentE2ETest.test_20_booking_payment_failure_e2e",
        ],
        "covered_paths": [
            "/api/bookings",
            "/api/webhooks/stripe",
            "/booking",
        ],
    },
    {
        "id": "suitedash-service-scaffolding",
        "title": "SuiteDash service scaffolding and admin integration status",
        "area": "Integrations",
        "health": "working",
        "status": "Automated",
        "summary": "Covers SuiteDash status/config helpers, contact meta request wiring, and admin-only integration status endpoints.",
        "source_file": "backend/tests/test_suitedash_service.py",
        "source_test": "SuiteDashServiceTest",
        "commands": [
            "venv/bin/python -m unittest tests.test_suitedash_service",
        ],
        "covered_paths": [
            "SuiteDash status helpers",
            "/api/admin/integrations/suitedash/status",
            "/api/admin/integrations/suitedash/contact-meta",
        ],
    },
    {
        "id": "booking-schema-validation-matrix",
        "title": "Booking schema validation matrix",
        "area": "Bookings",
        "health": "working",
        "status": "Automated",
        "summary": "Adds 42 fast validation cases covering duration rules, start-time alignment, room max duration rules, and staff-selection normalization.",
        "source_file": "backend/tests/test_booking_matrix.py",
        "source_test": "BookingSchemaMatrixTest",
        "commands": [
            "venv/bin/python -m unittest tests.test_booking_matrix.BookingSchemaMatrixTest",
        ],
        "covered_paths": [
            "booking schema validation",
            "reservation schema validation",
            "room max duration validation",
            "staff selection normalization",
        ],
    },
    {
        "id": "reservation-hold-matrix",
        "title": "Reservation hold memory matrix",
        "area": "Bookings",
        "health": "working",
        "status": "Automated",
        "summary": "Adds 12 hold-management cases covering hold creation, overlap blocking, expiry, release behavior, and multi-slot validation.",
        "source_file": "backend/tests/test_booking_matrix.py",
        "source_test": "ReservationHoldMatrixTest",
        "commands": [
            "venv/bin/python -m unittest tests.test_booking_matrix.ReservationHoldMatrixTest",
        ],
        "covered_paths": [
            "reservation holds",
            "slot locking",
            "hold expiry",
            "hold release",
        ],
    },
    {
        "id": "booking-service-regression-matrix",
        "title": "Booking service regression matrix",
        "area": "Bookings",
        "health": "working",
        "status": "Automated",
        "summary": "Adds 46 service-level booking cases covering availability, daily limits, admin bypasses, staff conflicts, payment state changes, refunds, and booking cleanup flows.",
        "source_file": "backend/tests/test_booking_matrix.py",
        "source_test": "BookingServiceMatrixTest",
        "commands": [
            "venv/bin/python -m unittest tests.test_booking_matrix.BookingServiceMatrixTest",
        ],
        "covered_paths": [
            "booking service rules",
            "availability calculation",
            "staff conflict detection",
            "pending payment expiry",
            "refund and webhook handling",
        ],
    },
    {
        "id": "runtime-config-development-stubs",
        "title": "Runtime config allows local development stubs",
        "area": "Launch",
        "health": "working",
        "status": "Automated",
        "summary": "Verifies development mode accepts the local stub keys and console delivery settings needed for local work.",
        "source_file": "backend/tests/test_runtime_config.py",
        "source_test": "test_development_allows_local_stub_settings",
        "commands": [
            "venv/bin/python -m unittest tests.test_runtime_config.RuntimeConfigurationTest.test_development_allows_local_stub_settings",
        ],
        "covered_paths": [
            "runtime configuration",
            "development environment",
        ],
    },
    {
        "id": "runtime-config-production-placeholders",
        "title": "Runtime config rejects placeholder production secrets",
        "area": "Launch",
        "health": "working",
        "status": "Automated",
        "summary": "Ensures production startup rejects placeholder Stripe, SendGrid, and app secrets before the app can boot.",
        "source_file": "backend/tests/test_runtime_config.py",
        "source_test": "test_production_rejects_placeholder_settings",
        "commands": [
            "venv/bin/python -m unittest tests.test_runtime_config.RuntimeConfigurationTest.test_production_rejects_placeholder_settings",
        ],
        "covered_paths": [
            "runtime configuration",
            "production environment",
            "placeholder secret validation",
        ],
    },
    {
        "id": "runtime-config-production-realistic",
        "title": "Runtime config accepts realistic production settings",
        "area": "Launch",
        "health": "working",
        "status": "Automated",
        "summary": "Confirms realistic live keys and URLs are accepted for a proper production deployment.",
        "source_file": "backend/tests/test_runtime_config.py",
        "source_test": "test_production_accepts_realistic_settings",
        "commands": [
            "venv/bin/python -m unittest tests.test_runtime_config.RuntimeConfigurationTest.test_production_accepts_realistic_settings",
        ],
        "covered_paths": [
            "runtime configuration",
            "production environment",
        ],
    },
    {
        "id": "runtime-config-twilio-placeholder-guard",
        "title": "Runtime config rejects placeholder Twilio credentials",
        "area": "Launch",
        "health": "working",
        "status": "Automated",
        "summary": "Prevents a production SMS setup from booting with placeholder Twilio credentials.",
        "source_file": "backend/tests/test_runtime_config.py",
        "source_test": "test_production_rejects_placeholder_twilio_settings",
        "commands": [
            "venv/bin/python -m unittest tests.test_runtime_config.RuntimeConfigurationTest.test_production_rejects_placeholder_twilio_settings",
        ],
        "covered_paths": [
            "runtime configuration",
            "twilio validation",
            "production environment",
        ],
    },
    {
        "id": "payment-webhook-idempotency-storm",
        "title": "Payment webhook duplicate-delivery storm handling",
        "area": "Payments",
        "health": "working",
        "status": "Automated",
        "summary": "Floods /api/webhooks/stripe with 20 duplicate payment_intent.succeeded events and asserts exactly one paid-audit entry plus one confirmation-email notification log.",
        "source_file": "backend/tests/backend/test_payments.py",
        "source_test": "test_31_webhook_duplicate_storm_is_idempotent",
        "commands": [],
        "covered_paths": [
            "/api/webhooks/stripe",
            "payment webhook idempotency",
        ],
    },
    {
        "id": "background-worker-retry-recovery",
        "title": "Background worker retry and recovery coverage",
        "area": "Operations",
        "health": "working",
        "status": "Automated",
        "summary": "Patches the email provider to raise, verifies the task writes a Failed notification log and re-raises for Celery retry, then proves the cleanup task is idempotent on a second invocation.",
        "source_file": "backend/tests/backend/test_ops.py",
        "source_test": "test_42_background_worker_recovery_when_providers_fail",
        "commands": [],
        "covered_paths": [
            "celery worker retries",
            "notification delivery recovery",
            "cleanup job recovery",
        ],
    },
    {
        "id": "live-provider-delivery-verification",
        "title": "Live email and SMS provider verification",
        "area": "Operations",
        "health": "working",
        "status": "Automated",
        "summary": "SendGrid `Mail` payload (from/to/subject/plain+html/reply-to/ICS attachment base64) and Twilio HTTP request (URL, Basic auth header, form-encoded To/From/Body, E.164 phone normalisation) are verified by tests/backend/test_notification_providers.py.",
        "source_file": "backend/app/services/notification_service.py",
        "source_test": "tests/backend/test_notification_providers.py",
        "commands": [
            "python -m unittest tests.backend.test_notification_providers",
        ],
        "covered_paths": [
            "sendgrid delivery",
            "twilio delivery",
            "provider sandbox verification",
        ],
    },
]


def list_admin_test_cases() -> list[dict]:
    return TEST_CASE_CATALOG
